# Generated by Django 5.2.14 on 2026-05-13 06:40

import django.db.models.deletion
import recurrence.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('xp_size', models.CharField(choices=[('XXS', 'XXS (0.5)'), ('XS', 'XS (1)'), ('S', 'S (2)'), ('M', 'M (3)'), ('L', 'L (5)'), ('XL', 'XL (8)'), ('XXL', 'XXL (13)'), ('XXXL', 'XXXL (21)')], default='M', max_length=4)),
                ('recurrence', recurrence.fields.RecurrenceField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore_definitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChoreInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_count', models.IntegerField(default=0)),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='chores.choredefinition')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('definition', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='ChoreCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField()),
                ('xp_earned', models.IntegerField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='chores.choreinstance')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=500)),
                ('required', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('ENUM', 'Enum')], default='TEXT', max_length=10)),
                ('regex_pattern', models.CharField(blank=True, max_length=200)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='chores.choredefinition')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='chores.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompletionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, null=True)),
                ('integer_value', models.IntegerField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='chores.chorecompletion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='chores.question')),
                ('enum_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='chores.questionchoice')),
            ],
        ),
    ]
