# Generated by Django 5.2.14 on 2026-05-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_streak_multiplier', models.FloatField(default=2.0)),
                ('streak_approach_rate', models.FloatField(default=0.1)),
                ('decay_approach_rate', models.FloatField(default=0.05)),
                ('decay_floor', models.FloatField(default=0.5)),
            ],
            options={
                'verbose_name': 'XP Settings',
                'verbose_name_plural': 'XP Settings',
            },
        ),
    ]
